name: Build Executables

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-amd64
            python-version: '3.11'
          - os: ubuntu-latest  
            platform: linux-arm64
            python-version: '3.11'
          - os: windows-latest
            platform: windows-amd64
            python-version: '3.11'
          - os: macos-latest
            platform: darwin-arm64
            python-version: '3.11'
          - os: macos-latest
            platform: darwin-amd64
            python-version: '3.11'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyotp cryptography

    - name: Build executable
      shell: bash
      run: |
        pyinstaller --onefile --name credmanager \
          --hidden-import pyotp \
          --hidden-import cryptography \
          --hidden-import settings_general \
          --hidden-import settings_export \
          --hidden-import settings_import \
          --hidden-import settings_structure \
          main.py

    - name: Rename executable for platform
      shell: bash
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          mv dist/credmanager.exe dist/credmanager-${{ matrix.platform }}.exe
        else
          mv dist/credmanager dist/credmanager-${{ matrix.platform }}
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: credmanager-${{ matrix.platform }}
        path: |
          dist/credmanager-${{ matrix.platform }}*
        retention-days: 90

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: List files
      run: find ./artifacts -type f

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./artifacts/**/*
